import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-providers";
import { ConvexClientProvider } from "@/providers/convex-client-providers";
import {Toaster} from "react-hot-toast"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatterBox!",
  description: "Generated by Kgpian",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange>
	<ConvexClientProvider>
  {children}
  <Toaster/>
  </ConvexClientProvider>
</ThemeProvider>
      </body>
    </html>
  );
}
